// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2raqtZ4HYr8DcU9S_aDgKOWtUlWnLzZw',
    appId: '1:225468805987:ios:c7713f2bcb1e170b2a9956',
    messagingSenderId: '225468805987',
    projectId: 'hipl-bsb-system',
    storageBucket: 'hipl-bsb-system.firebasestorage.app',
    iosBundleId: 'com.example.hiplBsbMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2raqtZ4HYr8DcU9S_aDgKOWtUlWnLzZw',
    appId: '1:225468805987:ios:c7713f2bcb1e170b2a9956',
    messagingSenderId: '225468805987',
    projectId: 'hipl-bsb-system',
    storageBucket: 'hipl-bsb-system.firebasestorage.app',
    iosBundleId: 'com.example.hiplBsbMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbTZtd5COwdpXXJFU3BP6y2BF1czhMZY',
    appId: '1:225468805987:web:bb7328ce9608e90c2a9956',
    messagingSenderId: '225468805987',
    projectId: 'hipl-bsb-system',
    authDomain: 'hipl-bsb-system.firebaseapp.com',
    storageBucket: 'hipl-bsb-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMV2aL0lr0Ndtw-6lg7NBnastdPpjkRVA',
    appId: '1:225468805987:android:2692d08dbb46cb6f2a9956',
    messagingSenderId: '225468805987',
    projectId: 'hipl-bsb-system',
    storageBucket: 'hipl-bsb-system.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGbTZtd5COwdpXXJFU3BP6y2BF1czhMZY',
    appId: '1:225468805987:web:48f7c6b61363a5432a9956',
    messagingSenderId: '225468805987',
    projectId: 'hipl-bsb-system',
    authDomain: 'hipl-bsb-system.firebaseapp.com',
    storageBucket: 'hipl-bsb-system.firebasestorage.app',
  );

}